services:
  - type: web
    name: radmir-jb-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_ID
        value: "5952642946"
      - key: CHECK_INTERVAL_MINUTES
        value: "10"
      - key: PAGES_TO_CHECK
        value: "3"
      - key: FORUM_URL
        value: "https://forum.radmir.games/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%BE%D0%B2-%D0%BD%D0%B5-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D1%85-%D0%B2%D0%BE-%D1%84%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D1%8F%D1%85.237/"
      - key: BOT_TOKEN
        sync: false
